<a href="https://colab.research.google.com/github/Yash0411/Machine-Learning-initial-projects/blob/master/AI_Tic_Tac_Toe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import csv
import numpy as np

# name of csv file  
filename = "/content/dataset2.csv"
fields = ['Box1','Box2','Box3','Box4','Box5','Box6','Box7','Box8','Box9','Predict']
# writing to csv file  
with open(filename, 'a') as csvfile:  
    # creating a csv writer object  
    csvwriter = csv.writer(csvfile)  
        
    # writing the fields  
    csvwriter.writerow(fields)  

    rows = 3
    cols = 3
    board_size = rows * cols



    class state:
      data = np.zeros((9,1))
      winner = None
      end = None
      turn = None
      state1 = None    

      def initiate(self):

        self.winner = None
        self.data = np.zeros((9,1)) 
        self.end = False
        self.turn = None
        self.state1 = self.data


        decide = int(input("Press : \n 1. P2 First \n 2. P1 First \n "))
        if decide == 1 :
          self.turn = 1
          self.play()
        elif decide == 2 :
          self.turn = 0
          self.play()
        else:
          self.initiate()

      
      def endgame(self):
        if self.data[0]==self.data[1]==self.data[2]==1 or self.data[3]==self.data[4]==self.data[5]==1 or self.data[6]==self.data[7]==self.data[8]==1:
          print("Player 1 Wins")
          return True
        elif self.data[0]==self.data[1]==self.data[2]==-1 or self.data[3]==self.data[4]==self.data[5]==-1 or self.data[6]==self.data[7]==self.data[8]==-1:
          print("Player 2 Wins")
          return True
        elif self.data[0]==self.data[3]==self.data[6]==1 or self.data[1]==self.data[4]==self.data[7]==1 or self.data[2]==self.data[5]==self.data[8]==1:
          print("Player 1 Wins")
          return True
        elif self.data[0]==self.data[3]==self.data[6]==-1 or self.data[1]==self.data[4]==self.data[7]==-1 or self.data[2]==self.data[5]==self.data[8]==-1:
          print("Player 2 Wins")
          return True
        elif self.data[0]==self.data[4]==self.data[8]==1 or self.data[2]==self.data[4]==self.data[6]==1:
          print("Player 1 Wins")
          return True
        elif self.data[0]==self.data[4]==self.data[8]==-1 or self.data[2]==self.data[4]==self.data[6]==-1:
          print("Player 2 Wins")
          return True
        
        return False



      def print_grid(self):
        c = 0
        for i in self.data:
          print(i, end=" ")
          c+=1
          if c%3==0:
            print("\n")
        print("\n\n")


      def play(self): 
        step = 0
        self.arr = self.data
        while self.end!=1 and step<9:

          self.state1 = self.data
          #print(p)
        
          if self.turn == 1 :
            
            x = int(input("Player 2 : "))

            p = np.reshape(self.state1,(9))
            p = p.tolist()
            p.append(x)
            csvwriter.writerow(p)

            self.make_a_move(x)
        
          elif self.turn == 0 :
            x = int(input("Player 1 : "))

            p = np.reshape(self.state1,(9))
            p = p.tolist()
            p.append(x)
            csvwriter.writerow(p)
            
            self.human_to_move(x)
          
          step+=1
          #print(p)
            


          #Check Winner ar is a Tie
          if self.endgame()!=False or step == 9:
            if self.endgame()==False:
              print("TIE")
            break


        

      def human_to_move(self,x):
        print("\nYour 1 Turn : \n")
        self.data[x-1][0] = 1
        self.turn = 1
        self.print_grid()


      def make_a_move(self,x):
        print("\nYour 2 Turn : \n")
        self.data[x-1][0] = -1
        self.turn = 0
        self.print_grid()

      

    z=1    
    s1 = state()
    while(z!=0) :  
      s1.initiate()
      z = int(input("Press 0 to quit Else any number: "))


Press : 
 1. P2 First 
 2. P1 First 
 1
Player 2 :  5

Your 2 Turn : 

[0.] [0.] [0.] 

[0.] [-1.] [0.] 

[0.] [0.] [0.] 




Player 1 : 7

Your 1 Turn : 

[0.] [0.] [0.] 

[0.] [-1.] [0.] 

[1.] [0.] [0.] 




Player 2 : 3

Your 2 Turn : 

[0.] [0.] [-1.] 

[0.] [-1.] [0.] 

[1.] [0.] [0.] 




Player 1 : 4

Your 1 Turn : 

[0.] [0.] [-1.] 

[1.] [-1.] [0.] 

[1.] [0.] [0.] 




Player 2 : 6

Your 2 Turn : 

[0.] [0.] [-1.] 

[1.] [-1.] [-1.] 

[1.] [0.] [0.] 




Player 1 : 1

Your 1 Turn : 

[1.] [0.] [-1.] 

[1.] [-1.] [-1.] 

[1.] [0.] [0.] 




Player 1 Wins
Player 1 Wins
Press 0 to quit Else any number: 1
Press : 
 1. P2 First 
 2. P1 First 
 1
Player 2 : 3

Your 2 Turn : 

[0.] [0.] [-1.] 

[0.] [0.] [0.] 

[0.] [0.] [0.] 




Player 1 : 5

Your 1 Turn : 

[0.] [0.] [-1.] 

[0.] [1.] [0.] 

[0.] [0.] [0.] 




Player 2 : 7

Your 2 Turn : 

[0.] [0.] [-1.] 

[0.] [1.] [0.] 

[-1.] [0.] [0.] 




Player 1 : 8

Your 1 Turn : 

[0.] [0.] [-1.] 

[0.] [1.] [0.] 

[-1.] [1.] [0.] 




In [3]:
from keras import Sequential
import tensorflow as tf
import pandas as pd
import numpy as np
import random

Using TensorFlow backend.


In [43]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(64, activation='relu', input_shape=(9,)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(256, activation='relu'),
  tf.keras.layers.Dense(512, activation='relu'),
  tf.keras.layers.Dense(256, activation='relu'),
  tf.keras.layers.Dense(128, activation='relu'),      
  tf.keras.layers.Dense(9, activation='softmax'),                            
])
model.compile(loss='categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_26 (Dense)             (None, 64)                640       
_________________________________________________________________
dense_27 (Dense)             (None, 128)               8320      
_________________________________________________________________
dense_28 (Dense)             (None, 256)               33024     
_________________________________________________________________
dense_29 (Dense)             (None, 512)               131584    
_________________________________________________________________
dense_30 (Dense)             (None, 256)               131328    
_________________________________________________________________
dense_31 (Dense)             (None, 128)               32896     
_________________________________________________________________
dense_32 (Dense)             (None, 9)                

In [44]:
'''train = pd.read_csv("./dataset1.csv").values
print(train.shape)
train = train[:]
print(train[:10])

trainX = train[:,:9].astype( 'float32' )
x_train = trainX
print(x_train.shape)

y_train = train[:,9:10].astype( 'float32' )
y_train = tf.one_hot(y_train, 9)
#y_train = tf.transpose(y_train)
y_train = np.reshape(y_train,(y_train.shape[0],9))
print(y_train[:10])
print(y_train.shape)'''


train = pd.read_csv("./dataset.csv").values
print(train.shape)
val = train[70000:]
train = train[:70000]
print(train[-10:])



# Reshape and normalize training data

trainX = train[:,:9].astype( 'float32' )
x_train = trainX
print(x_train.shape)

y_train = train[:,9:10].astype( 'float32' )
print(y_train[-10:])
y_train = tf.one_hot(y_train, 9)
#y_train = tf.transpose(y_train)
y_train = np.reshape(y_train,(y_train.shape[0],9))

print(y_train[-10:])
print(y_train.shape)


valX = val[:,:9].astype( 'float32' )
x_val = valX
print(x_val.shape)

y_val = val[:,9:10].astype( 'float32' )
y_val = tf.one_hot(y_val, 9)
#y_train = tf.transpose(y_train)
y_val = np.reshape(y_val,(y_val.shape[0],9))




(74209, 10)
[[-1.  1.  1. -1.  0.  0.  0.  1.  1.  6.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  7.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  3.]
 [ 0.  0.  0. -1.  0.  0.  0.  1.  0.  8.]
 [ 0.  0.  0. -1.  0.  0.  0.  1.  1.  4.]
 [ 0.  0.  0. -1. -1.  0.  0.  1.  1.  6.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  5.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  1.  0.  0.  0.  8.]
 [ 1.  0.  0.  0.  0.  1.  0.  0. -1.  4.]]
(70000, 9)
[[6.]
 [7.]
 [3.]
 [8.]
 [4.]
 [6.]
 [5.]
 [0.]
 [8.]
 [4.]]
[[0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]]
(70000, 9)
(4209, 9)


In [21]:
z = game.trainingHistory
train = []
for i in z:
  train.append(i[1])
print(train[:10])

train = np.array(train)
trainX = train[:,:9].astype( 'float32' )
x_train = trainX
print(x_train.shape)

y_train = train[:,9:10].astype( 'float32' )
y_train = tf.one_hot(y_train, 9)
#y_train = tf.transpose(y_train)
y_train = np.reshape(y_train,(y_train.shape[0],9))

print(y_train[:10])
print(y_train.shape)


NameError: ignored

In [45]:
history = model.fit(x_train,y_train,
                    epochs = 10,
                    validation_data=(x_val,y_val))

Epoch 1/10
2188/2188 [==============================] - 12s 5ms/step - loss: 1.8342 - accuracy: 0.2303 - val_loss: 1.6896 - val_accuracy: 0.2476
Epoch 2/10
2188/2188 [==============================] - 12s 5ms/step - loss: 1.6752 - accuracy: 0.2499 - val_loss: 1.6571 - val_accuracy: 0.2526
Epoch 3/10
2188/2188 [==============================] - 12s 5ms/step - loss: 1.6624 - accuracy: 0.2520 - val_loss: 1.6577 - val_accuracy: 0.2492
Epoch 4/10
2188/2188 [==============================] - 12s 5ms/step - loss: 1.6621 - accuracy: 0.2485 - val_loss: 1.7454 - val_accuracy: 0.2483
Epoch 5/10
2188/2188 [==============================] - 12s 5ms/step - loss: 1.6642 - accuracy: 0.2495 - val_loss: 1.6688 - val_accuracy: 0.2373
Epoch 6/10
2188/2188 [==============================] - 12s 5ms/step - loss: 1.6666 - accuracy: 0.2507 - val_loss: 1.6530 - val_accuracy: 0.2426
Epoch 7/10
2188/2188 [==============================] - 12s 5ms/step - loss: 1.6725 - accuracy: 0.2477 - val_loss: 1.6487 - val_ac

In [0]:
model.save("tic_tac_toe.h5")

In [27]:
rows = 3
cols = 3
board_size = rows * cols

class state:
  data = np.zeros((9,1))
  winner = None
  end = None
  turn = None
  
    

  def initiate(self):

    self.winner = None
    self.data = np.zeros((9,1)) 
    self.end = False
    self.turn = None


    decide = int(input("Press : \n 1. Computer First \n 2. Human First \n "))
    if decide == 1 :
      self.turn = 1
      self.play()
    elif decide == 2 :
      self.turn = 0
      self.play()
    else:
      self.initiate()

  
  def endgame(self):
    if self.data[0]==self.data[1]==self.data[2]==1 or self.data[3]==self.data[4]==self.data[5]==1 or self.data[6]==self.data[7]==self.data[8]==1:
      print("AI Wins")
      return True
    elif self.data[0]==self.data[1]==self.data[2]==-1 or self.data[3]==self.data[4]==self.data[5]==-1 or self.data[6]==self.data[7]==self.data[8]==-1:
      print("Player Wins")
      return True
    elif self.data[0]==self.data[3]==self.data[6]==1 or self.data[1]==self.data[4]==self.data[7]==1 or self.data[2]==self.data[5]==self.data[8]==1:
      print("AI Wins")
      return True
    elif self.data[0]==self.data[3]==self.data[6]==-1 or self.data[1]==self.data[4]==self.data[7]==-1 or self.data[2]==self.data[5]==self.data[8]==-1:
      print("Player Wins")
      return True
    elif self.data[0]==self.data[4]==self.data[8]==1 or self.data[2]==self.data[4]==self.data[6]==1:
      print("AI Wins")
      return True
    elif self.data[0]==self.data[4]==self.data[8]==-1 or self.data[2]==self.data[4]==self.data[6]==-1:
      print("Player Wins")
      return True
    
    return False



  def print_grid(self):
    c = 0
    for i in self.data:
      print(i, end=" ")
      c+=1
      if c%3==0:
        print("\n")
    print("\n\n")


  def play(self): 
    step = 0

    while self.end!=1 and step<9:
    
      if self.turn == 1 :
        self.make_a_move()
    
      elif self.turn == 0 :
        self.human_to_move()
      
      step+=1

      #Check Winner ar is a Tie
      if self.endgame()!=False or step == 9:
        if self.endgame()==False:
          print("TIE")
        break



  def human_to_move(self):
    x = int(input("Player : "))
    if self.data[x-1]==0:
      print("\nYour Turn : \n")
      self.data[x-1][0] = 1
      self.turn = 1
      self.print_grid()
    else : 
      print("Enter proper value")
      self.human_to_move()


  def make_a_move(self):
    print("\nComputer's Turn : \n")
    l=model.predict(np.transpose(self.data))
    k = l.argmax()
    print(k,l)
    if self.data[k]!=0:
      while self.data[k]!=0:
        print(l,k)
        l[0][k]=0
        k = l.argmax()
    print(k)
    self.data[k][0] = -1
    self.turn = 0
    self.print_grid()

      
    
s1 = state()
s1.initiate()

Press : 
 1. Computer First 
 2. Human First 
 2
Player : 5

Your Turn : 

[0.] [0.] [0.] 

[0.] [1.] [0.] 

[0.] [0.] [0.] 





Computer's Turn : 

0 [[1.61282793e-01 1.22731648e-01 1.29949555e-01 1.17461018e-01
  6.92261498e-27 1.18705601e-01 1.13423176e-01 1.17582954e-01
  1.18863299e-01]]
0
[-1.] [0.] [0.] 

[0.] [1.] [0.] 

[0.] [0.] [0.] 




Player : 9

Your Turn : 

[-1.] [0.] [0.] 

[0.] [1.] [0.] 

[0.] [0.] [1.] 





Computer's Turn : 

7 [[1.0671765e-08 1.2495511e-01 1.9495995e-01 1.4422242e-01 0.0000000e+00
  2.0258710e-01 1.3039753e-01 2.0287789e-01 3.5981365e-10]]
7
[-1.] [0.] [0.] 

[0.] [1.] [0.] 

[0.] [-1.] [1.] 




Player : 3

Your Turn : 

[-1.] [0.] [1.] 

[0.] [1.] [0.] 

[0.] [-1.] [1.] 





Computer's Turn : 

6 [[1.4455253e-14 1.8575414e-01 0.0000000e+00 2.8300792e-01 1.1445228e-34
  2.1620311e-01 3.1503484e-01 1.8674221e-18 3.4666254e-09]]
6
[-1.] [0.] [1.] 

[0.] [1.] [0.] 

[-1.] [-1.] [1.] 




Player : 6

Your Turn : 

[-1.] [0.] [1.] 

[0.] [1.] [1.]

In [0]:
!pip install tensorflowjs
import tensorflowjs as tfjs
tfjs.converters.save_keras_model(model,"/content/")

In [41]:
import csv
import numpy as np
import pandas as pd
import os
import random

# name of csv file  
filename = "/content/dataset.csv"
fields = ['Box1','Box2','Box3','Box4','Box5','Box6','Box7','Box8','Box9','Predict']
# writing to csv file  
with open(filename, 'w') as csvfile:  
    # creating a csv writer object  
    csvwriter = csv.writer(csvfile)  
        
    # writing the fields  
    csvwriter.writerow(fields)  

    rows = 3
    cols = 3
    board_size = rows * cols


    class state:
      data = np.zeros((9,1))
      winner = None
      end = None
      turn = None
      state1 = None
      state2 = None
      dec = 0  
      X = 0
      O = 0
      D = 0

      def initiate(self,z):

        self.winner = None
        self.data = np.zeros((9,1)) 
        self.end = False
        self.turn = None
        self.state1 = self.data
        self.state2 = []
        self.dec +=1

        
        decide = z%2+1
        k = int((random.random()*10)%9)
        self.state1 = self.data
        p = np.reshape(self.state1,(9))
        p = p.tolist()
        p.append(k)
        self.state2.append(p)

        #decide = int(input("Press : \n 1. Computer First \n 2. Human First \n "))
        if decide == 1 :
          self.data[k]=1
          self.turn = 0
          self.play()
        elif decide == 2 :
          self.data[k]=1
          self.turn = 1
          self.play()
        else:
          self.initiate()

      
      def endgame(self):
        if self.data[0]==self.data[1]==self.data[2]==1 or self.data[3]==self.data[4]==self.data[5]==1 or self.data[6]==self.data[7]==self.data[8]==1:
          print("AI Wins")
          return -1
        elif self.data[0]==self.data[1]==self.data[2]==-1 or self.data[3]==self.data[4]==self.data[5]==-1 or self.data[6]==self.data[7]==self.data[8]==-1:
          print("Player Wins")
          return 1
        elif self.data[0]==self.data[3]==self.data[6]==1 or self.data[1]==self.data[4]==self.data[7]==1 or self.data[2]==self.data[5]==self.data[8]==1:
          print("AI Wins")
          return -1
        elif self.data[0]==self.data[3]==self.data[6]==-1 or self.data[1]==self.data[4]==self.data[7]==-1 or self.data[2]==self.data[5]==self.data[8]==-1:
          print("Player Wins")
          return 1
        elif self.data[0]==self.data[4]==self.data[8]==1 or self.data[2]==self.data[4]==self.data[6]==1:
          print("AI Wins")
          return -1
        elif self.data[0]==self.data[4]==self.data[8]==-1 or self.data[2]==self.data[4]==self.data[6]==-1:
          print("Player Wins")
          return 1
        
        return 0



      def print_grid(self):
        c = 0
        for i in self.data:
          print(i, end=" ")
          c+=1
          if c%3==0:
            print("\n")
        print("\n\n")


      def play(self): 
        self.step = 1

        while self.end!=1 and self.step<9:
        
          if self.turn == 1 :
            self.make_a_move()
        
          elif self.turn == 0 :
            self.human_to_move()
          
          self.step+=1

          #Check Winner ar is a Tie
          if self.endgame()!=0 or self.step == 9:
            if self.endgame()==0:
              print("TIE")
              csvwriter.writerows(self.state2)
              self.D+=1
            else:
              if self.endgame()==1:
                csvwriter.writerows(self.state2)
                self.X +=1
                break
              else:
                csvwriter.writerows(self.state2)
                self.O+=1
                break



      def getAvailableMoves(self):
        availableMoves = []
        for i in range(len(self.data)):
          if (self.data[i]) == 0:
                    availableMoves.append(i)
        return availableMoves


      def human_to_move(self):
        self.state1 = self.data
        p = np.reshape(self.state1,(9))
        p = p.tolist()
        availableMoves = self.getAvailableMoves()
        selectedMove = availableMoves[random.randrange(0, len(availableMoves))]
        p.append(selectedMove)
        for i in range(len(availableMoves)):
            if selectedMove == availableMoves[i]:
                self.data[selectedMove] = 1


        #print("\nComputer's Turn : \n")
        '''l=model.predict(np.transpose(self.data))
        k = l.argmax()
        print(k,l)
        if self.data[k]!=0:
          while self.data[k]!=0:
            print(l,k+1)
            l[0][k]=0
            k = l.argmax()
        #print(k)

        
        
        p = np.reshape(self.state1,(9))
        p = p.tolist()
        p.append(k+1)
        self.state2.append(p)

        self.data[k][0] = 1'''
        self.turn = 1
        self.state2.append(p)
        #self.print_grid()


      def make_a_move(self):
        self.state1 = self.data
        p = np.reshape(self.state1,(9))
        p = p.tolist()
        availableMoves = self.getAvailableMoves()
        selectedMove = availableMoves[random.randrange(0, len(availableMoves))]
        p.append(selectedMove)
        for i in range(len(availableMoves)):
            if selectedMove == availableMoves[i]:
                self.data[selectedMove] = -1

        '''#print("\nComputer's Turn : \n")
        l=model.predict(np.transpose(self.data))
        k = l.argmax()
        print(k,l)
        if self.data[k]!=0:
          while self.data[k]!=0:
            print(l,k+1)
            l[0][k]=0
            k = l.argmax()
        #print(k)

        
        self.state1 = self.data
        p = np.reshape(self.state1,(9))
        p = p.tolist()
        p.append(k+1)
        self.state2.append(p)

        self.data[k][0] = -1'''
        self.turn = 0
        self.state2.append(p)
        #self.print_grid()

      

    z=1    
    s1 = state()
    while(z!=10000) :  
      s1.initiate(z)
      #z = int(input("Press 0 to quit Else any number: "))
      z+=1
    print("X Win :", s1.X)
    print("O Win :", s1.O)
    print("Draw :", s1.D)


Streaming output truncated to the last 5000 lines.
Player Wins
Player Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
Player Wins
Player Wins
Player Wins
AI Wins
AI Wins
AI Wins
Player Wins
Player Wins
Player Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
TIE
AI Wins
AI Wins
AI Wins
TIE
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
Player Wins
Player Wins
Player Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
TIE
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
TIE
AI Wins
AI Wins
AI Wins
Player Wins
Player Wins
Player Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
TIE
Player Wins
Player Wins
Player Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
Player Wins
Player Wins
Player Wins
AI Wins
AI Wins
AI Wins
AI Wins
AI Wins
A

In [0]:
train = pd.read_csv("./dataset.csv").values
print(len(train))
p=[0.,0.,0.,0.,0.,0.,0.,0.,0.]
z = [0]*9
c=0
for i in train:
  k = list(i[:9])
  if k==p:
    c+=1
    z[int(i[9])]+=1
print(c)
print(z)

57755
7884
[1627, 744, 772, 729, 908, 715, 787, 751, 851]


In [0]:
from keras.layers import Dense
from keras.layers import Dropout
from keras.models import Sequential
from keras.utils import to_categorical
import numpy as np


class TicTacToeModel:

    def __init__(self, numberOfInputs, numberOfOutputs, epochs, batchSize):
        self.epochs = epochs
        self.batchSize = batchSize
        self.numberOfInputs = numberOfInputs
        self.numberOfOutputs = numberOfOutputs
        self.model = Sequential()
        self.model.add(Dense(64, activation='relu', input_shape=(numberOfInputs, )))
        self.model.add(Dense(128, activation='relu'))
        self.model.add(Dense(128, activation='relu'))
        self.model.add(Dense(128, activation='relu'))
        self.model.add(Dense(numberOfOutputs, activation='softmax'))
        self.model.compile(loss='categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

    def train(self, dataset):
        input = []
        output = []
        for data in dataset:
            input.append(data[1])
            output.append(data[0])

        X = np.array(input).reshape((-1, self.numberOfInputs))
        y = to_categorical(output, num_classes=3)
        # Train and test data split
        boundary = int(0.8 * len(X))
        X_train = X[:boundary]
        X_test = X[boundary:]
        y_train = y[:boundary]
        y_test = y[boundary:]
        self.model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=self.epochs, batch_size=self.batchSize)

    def predict(self, data, index):
        return self.model.predict(np.array(data).reshape(-1, self.numberOfInputs))[0][index]

In [0]:
import os
import random
import copy

PLAYER_X = 'X'
PLAYER_O = 'O'
EMPTY = ' '
PLAYER_X_VAL = -1
PLAYER_O_VAL = 1
EMPTY_VAL = 0
HORIZONTAL_SEPARATOR = ' | '
VERTICAL_SEPARATOR = '---------------'
GAME_STATE_X = -1
GAME_STATE_O = 1
GAME_STATE_DRAW = 0
GAME_STATE_NOT_ENDED = 2


class Game:

    def __init__(self):
        self.resetBoard()
        self.trainingHistory = []

    def resetBoard(self):
        self.board = [
            [0, 0, 0],
            [0, 0, 0],
            [0, 0, 0]
        ]
        self.boardHistory = []

    def printBoard(self):
        print(VERTICAL_SEPARATOR)
        for i in range(len(self.board)):
            print(' ', end='')
            for j in range(len(self.board[i])):
                if PLAYER_X_VAL == self.board[i][j]:
                    print(PLAYER_X, end='')
                elif PLAYER_O_VAL == self.board[i][j]:
                    print(PLAYER_O, end='')
                elif EMPTY_VAL == self.board[i][j]:
                    print(EMPTY, end='')
                print(HORIZONTAL_SEPARATOR, end='')
            print(os.linesep)
            print(VERTICAL_SEPARATOR)

    def getGameResult(self):
        for i in range(len(self.board)):
            for j in range(len(self.board[i])):
                if self.board[i][j] == EMPTY_VAL:
                    return GAME_STATE_NOT_ENDED

        # Rows
        for i in range(len(self.board)):
            candidate = self.board[i][0]
            for j in range(len(self.board[i])):
                if candidate != self.board[i][j]:
                    candidate = 0
            if candidate != 0:
                return candidate

        # Columns
        for i in range(len(self.board)):
            candidate = self.board[0][i]
            for j in range(len(self.board[i])):
                if candidate != self.board[j][i]:
                    candidate = 0
            if candidate != 0:
                return candidate

        # First diagonal
        candidate = self.board[0][0]
        for i in range(len(self.board)):
            if candidate != self.board[i][i]:
                candidate = 0
        if candidate != 0:
            return candidate

        # Second diagonal
        candidate = self.board[0][2]
        for i in range(len(self.board)):
            if candidate != self.board[i][len(self.board[i]) - i - 1]:
                candidate = 0
        if candidate != 0:
            return candidate

        return GAME_STATE_DRAW


    def getAvailableMoves(self):
        availableMoves = []
        for i in range(len(self.board)):
            for j in range(len(self.board[i])):
                if (self.board[i][j]) == EMPTY_VAL:
                    availableMoves.append([i, j])
        return availableMoves

    def addToHistory(self, board):
        self.boardHistory.append(board)

    def printHistory(self):
        print(self.boardHistory)

    def move(self, position, player):
        availableMoves = self.getAvailableMoves()
        for i in range(len(availableMoves)):
            if position[0] == availableMoves[i][0] and position[1] == availableMoves[i][1]:
                self.board[position[0]][position[1]] = player
                self.addToHistory(copy.deepcopy(self.board))


    def simulate(self, playerToMove):
        while (self.getGameResult() == GAME_STATE_NOT_ENDED):
            availableMoves = self.getAvailableMoves()
            selectedMove = availableMoves[random.randrange(0, len(availableMoves))]
            self.move(selectedMove, playerToMove)
            if playerToMove == PLAYER_X_VAL:
                playerToMove = PLAYER_O_VAL
            else:
                playerToMove = PLAYER_X_VAL
        # Get the history and build the training set
        for historyItem in self.boardHistory:
            self.trainingHistory.append((self.getGameResult(), copy.deepcopy(historyItem)))

    def simulateNeuralNetwork(self, nnPlayer, model):
        playerToMove = PLAYER_X_VAL
        while (self.getGameResult() == GAME_STATE_NOT_ENDED):
            availableMoves = self.getAvailableMoves()
            if playerToMove == nnPlayer:
                maxValue = 0
                bestMove = availableMoves[0]
                for availableMove in availableMoves:
                    # get a copy of a board
                    boardCopy = copy.deepcopy(self.board)
                    boardCopy[availableMove[0]][availableMove[1]] = nnPlayer
                    if nnPlayer == PLAYER_X_VAL:
                        value = model.predict(boardCopy, 0)
                    else:
                        value = model.predict(boardCopy, 2)
                    if value > maxValue:
                        maxValue = value
                        bestMove = availableMove
                selectedMove = bestMove
            else:
                selectedMove = availableMoves[random.randrange(0, len(availableMoves))]
            self.move(selectedMove, playerToMove)
            if playerToMove == PLAYER_X_VAL:
                playerToMove = PLAYER_O_VAL
            else:
                playerToMove = PLAYER_X_VAL

    def getTrainingHistory(self):
        return self.trainingHistory

    def simulateManyGames(self, playerToMove, numberOfGames):
        playerXWins = 0
        playerOWins = 0
        draws = 0
        for i in range(numberOfGames):
            self.resetBoard()
            self.simulate(playerToMove)
            if self.getGameResult() == PLAYER_X_VAL:
                playerXWins = playerXWins + 1
            elif self.getGameResult() == PLAYER_O_VAL:
                playerOWins = playerOWins + 1
            else: draws = draws + 1
        totalWins = playerXWins + playerOWins + draws
        print ('X Wins: ' + str(int(playerXWins * 100/totalWins)) + '%')
        print('O Wins: ' + str(int(playerOWins * 100 / totalWins)) + '%')
        print('Draws: ' + str(int(draws * 100 / totalWins)) + '%')


    def simulateManyNeuralNetworkGames(self, nnPlayer, numberOfGames, model):
        nnPlayerWins = 0
        randomPlayerWins = 0
        draws = 0
        print ("NN player")
        print (nnPlayer)
        for i in range(numberOfGames):
            self.resetBoard()
            self.simulateNeuralNetwork(nnPlayer, model)
            if self.getGameResult() == nnPlayer:
                nnPlayerWins = nnPlayerWins + 1
            elif self.getGameResult() == GAME_STATE_DRAW:
                draws = draws + 1
            else: randomPlayerWins = randomPlayerWins + 1
        totalWins = nnPlayerWins + randomPlayerWins + draws
        print ('X Wins: ' + str(int(nnPlayerWins * 100/totalWins)) + '%')
        print('O Wins: ' + str(int(randomPlayerWins * 100 / totalWins)) + '%')
        print('Draws: ' + str(int(draws * 100 / totalWins)) + '%')

if __name__ == "__main__":
    game = Game()
    game.simulateManyGames(1, 10000)
    ticTacToeModel = TicTacToeModel(9, 3, 100, 32)
    ticTacToeModel.train(game.getTrainingHistory())
    print ("Simulating with Neural Network as X Player:")
    game.simulateManyNeuralNetworkGames(PLAYER_X_VAL, 10, ticTacToeModel)
    print("Simulating with Neural Network as O Player:")
    game.simulateManyNeuralNetworkGames(PLAYER_O_VAL, 10, ticTacToeModel)

X Wins: 23%
O Wins: 63%
Draws: 12%
Train on 72000 samples, validate on 18000 samples
Epoch 1/100
72000/72000 [==============================] - 4s 53us/step - loss: 0.6100 - accuracy: 0.7344 - val_loss: 0.5546 - val_accuracy: 0.7601
Epoch 2/100
72000/72000 [==============================] - 4s 52us/step - loss: 0.5562 - accuracy: 0.7500 - val_loss: 0.5378 - val_accuracy: 0.7603
Epoch 3/100
72000/72000 [==============================] - 4s 51us/step - loss: 0.5481 - accuracy: 0.7520 - val_loss: 0.5358 - val_accuracy: 0.7604
Epoch 4/100
72000/72000 [==============================] - 4s 51us/step - loss: 0.5464 - accuracy: 0.7516 - val_loss: 0.5395 - val_accuracy: 0.7609
Epoch 5/100
72000/72000 [==============================] - 4s 51us/step - loss: 0.5443 - accuracy: 0.7516 - val_loss: 0.5283 - val_accuracy: 0.7619
Epoch 6/100
72000/72000 [==============================] - 4s 51us/step - loss: 0.5461 - accuracy: 0.7519 - val_loss: 0.5375 - val_accuracy: 0.7631
Epoch 7/100
72000/72000 [==

In [0]:
print(game.trainingHistory[:10])

[(1, [[0, 0, 0], [0, 0, 0], [1, 0, 0]]), (1, [[0, 0, 0], [0, 0, -1], [1, 0, 0]]), (1, [[0, 0, 0], [0, 0, -1], [1, 1, 0]]), (1, [[0, -1, 0], [0, 0, -1], [1, 1, 0]]), (1, [[0, -1, 0], [0, 0, -1], [1, 1, 1]]), (1, [[0, -1, 0], [0, -1, -1], [1, 1, 1]]), (1, [[0, -1, 1], [0, -1, -1], [1, 1, 1]]), (1, [[-1, -1, 1], [0, -1, -1], [1, 1, 1]]), (1, [[-1, -1, 1], [1, -1, -1], [1, 1, 1]]), (-1, [[0, 0, 0], [0, 1, 0], [0, 0, 0]])]


In [0]:
  
import os
import random
import copy

PLAYER_X = 'X'
PLAYER_O = 'O'
EMPTY = ' '
PLAYER_X_VAL = -1
PLAYER_O_VAL = 1
EMPTY_VAL = 0
HORIZONTAL_SEPARATOR = ' | '
VERTICAL_SEPARATOR = '---------------'
GAME_STATE_X = -1
GAME_STATE_O = 1
GAME_STATE_DRAW = 0
GAME_STATE_NOT_ENDED = 2


class Game:

    def __init__(self):
        self.resetBoard()
        self.trainingHistory = []

    def resetBoard(self):
        self.board = [0.,0.,0.,0.,0.,0.,0.,0.,0.]
        
        self.boardHistory = []

    def printBoard(self):
        c = 0
        for i in self.data:
          print(i, end=" ")
          c+=1
          if c%3==0:
            print("\n")
        print("\n\n")

    def getGameResult(self):
        for i in range(len(self.board)):
          if self.board[i] == EMPTY_VAL:
            return GAME_STATE_NOT_ENDED

        # Rows
        for i in range(len(self.board),3):
            candidate = self.board[i]
            for j in range(3):
                if candidate != self.board[i+j]:
                    candidate = 0
            if candidate != 0:
                return candidate

        # Columns
        for i in range(len(self.board)//3):
            candidate = self.board[i]
            for j in range(3):
                if candidate != self.board[i+j*3]:
                    candidate = 0
            if candidate != 0:
                return candidate

        # First diagonal
        candidate = self.board[0]
        for i in [0,4,8]:
            if candidate != self.board[i]:
                candidate = 0
        if candidate != 0:
            return candidate

        # Second diagonal
        candidate = self.board[2]
        for i in [2,4,6]:
            if candidate != self.board[i]:
                candidate = 0
        if candidate != 0:
            return candidate

        return GAME_STATE_DRAW

        '''self.data = self.board
        if self.data[0]==self.data[1]==self.data[2]==1 or self.data[3]==self.data[4]==self.data[5]==1 or self.data[6]==self.data[7]==self.data[8]==1:
          print("AI Wins")
          return -1
        elif self.data[0]==self.data[1]==self.data[2]==-1 or self.data[3]==self.data[4]==self.data[5]==-1 or self.data[6]==self.data[7]==self.data[8]==-1:
          print("Player Wins")
          return 1
        elif self.data[0]==self.data[3]==self.data[6]==1 or self.data[1]==self.data[4]==self.data[7]==1 or self.data[2]==self.data[5]==self.data[8]==1:
          print("AI Wins")
          return -1
        elif self.data[0]==self.data[3]==self.data[6]==-1 or self.data[1]==self.data[4]==self.data[7]==-1 or self.data[2]==self.data[5]==self.data[8]==-1:
          print("Player Wins")
          return 1
        elif self.data[0]==self.data[4]==self.data[8]==1 or self.data[2]==self.data[4]==self.data[6]==1:
          print("AI Wins")
          return -1
        elif self.data[0]==self.data[4]==self.data[8]==-1 or self.data[2]==self.data[4]==self.data[6]==-1:
          print("Player Wins")
          return 1
        elif self.draw==1:
          return 0
        
        return 2'''

    
    def draw(self):
      for i in self.board:
        if i[0]==0:
          return -1
      return 1


    def getAvailableMoves(self):
        availableMoves = []
        for i in range(len(self.board)):
          if (self.board[i]) == 0:
              availableMoves.append(i)
        return availableMoves


    def addToHistory(self, board):
        self.boardHistory.append(board)

    def printHistory(self):
        print(self.boardHistory)

    def move(self, position, player):
        availableMoves = self.getAvailableMoves()
        for i in range(len(availableMoves)):
            if position == availableMoves[i]:
                p = self.board
                p.append(float(position))
                self.addToHistory(copy.deepcopy(p))
                p.pop()
                self.board[position] = player


    def simulate(self, playerToMove):
        while (self.getGameResult() == GAME_STATE_NOT_ENDED):
            availableMoves = self.getAvailableMoves()
            if availableMoves==[]:
              break
            selectedMove = availableMoves[random.randrange(0, len(availableMoves))]
            self.move(selectedMove, playerToMove)
            if playerToMove == PLAYER_X_VAL:
                playerToMove = PLAYER_O_VAL
            else:
                playerToMove = PLAYER_X_VAL
        # Get the history and build the training set
        for historyItem in self.boardHistory:
            self.trainingHistory.append((self.getGameResult(), copy.deepcopy(historyItem)))

    '''def simulateNeuralNetwork(self, nnPlayer, model):
        playerToMove = PLAYER_X_VAL
        while (self.getGameResult() == GAME_STATE_NOT_ENDED):
            availableMoves = self.getAvailableMoves()
            if playerToMove == nnPlayer:
                maxValue = 0
                bestMove = availableMoves[0]
                for availableMove in availableMoves:
                    # get a copy of a board
                    boardCopy = copy.deepcopy(self.board)
                    boardCopy[availableMove[0]][availableMove[1]] = nnPlayer
                    if nnPlayer == PLAYER_X_VAL:
                        value = model.predict(boardCopy, 0)
                    else:
                        value = model.predict(boardCopy, 2)
                    if value > maxValue:
                        maxValue = value
                        bestMove = availableMove
                selectedMove = bestMove
            else:
                selectedMove = availableMoves[random.randrange(0, len(availableMoves))]
            self.move(selectedMove, playerToMove)
            if playerToMove == PLAYER_X_VAL:
                playerToMove = PLAYER_O_VAL
            else:
                playerToMove = PLAYER_X_VAL'''

    def getTrainingHistory(self):
        return self.trainingHistory

    def simulateManyGames(self, playerToMove, numberOfGames):
        playerXWins = 0
        playerOWins = 0
        draws = 0
        for i in range(numberOfGames):
            self.resetBoard()
            self.simulate(playerToMove)
            if self.getGameResult() == PLAYER_X_VAL:
                playerXWins = playerXWins + 1
            elif self.getGameResult() == PLAYER_O_VAL:
                playerOWins = playerOWins + 1
            else: draws = draws + 1
        totalWins = playerXWins + playerOWins + draws
        print ('X Wins: ' + str(int(playerXWins * 100/totalWins)) + '%')
        print('O Wins: ' + str(int(playerOWins * 100 / totalWins)) + '%')
        print('Draws: ' + str(int(draws * 100 / totalWins)) + '%')


    '''def simulateManyNeuralNetworkGames(self, nnPlayer, numberOfGames, model):
        nnPlayerWins = 0
        randomPlayerWins = 0
        draws = 0
        print ("NN player")
        print (nnPlayer)
        for i in range(numberOfGames):
            self.resetBoard()
            self.simulateNeuralNetwork(nnPlayer, model)
            if self.getGameResult() == nnPlayer:
                nnPlayerWins = nnPlayerWins + 1
            elif self.getGameResult() == GAME_STATE_DRAW:
                draws = draws + 1
            else: randomPlayerWins = randomPlayerWins + 1
        totalWins = nnPlayerWins + randomPlayerWins + draws
        print ('X Wins: ' + str(int(nnPlayerWins * 100/totalWins)) + '%')
        print('O Wins: ' + str(int(randomPlayerWins * 100 / totalWins)) + '%')
        print('Draws: ' + str(int(draws * 100 / totalWins)) + '%')

      def print1(self):
        print(self.trainingHistory)'''

if __name__ == "__main__":
    game = Game()
    game.simulateManyGames(1, 5000)
    #ticTacToeModel = TicTacToeModel(9, 3, 100, 32)
    #ticTacToeModel.train(game.getTrainingHistory())
    

X Wins: 16%
O Wins: 46%
Draws: 36%


In [0]:
z = game.trainingHistory   


import csv
import numpy as np
import pandas as pd
import os
import random

# name of csv file  
filename = "/content/dataset1.csv"
fields = ['Box1','Box2','Box3','Box4','Box5','Box6','Box7','Box8','Box9','Predict']
# writing to csv file  
with open(filename, 'w') as csvfile: 
  # creating a csv writer object  
  csvwriter = csv.writer(csvfile)  
        
  # writing the fields  
  csvwriter.writerow(fields) 
    
  for i in z[:]:
    csvwriter.writerow(i[1])
  
    


[(1, [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]), (1, [0.0, 1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.0]), (1, [0.0, 1, 0.0, 0.0, 0.0, 0.0, -1, 0.0, 0.0, 2.0]), (1, [0.0, 1, 1, 0.0, 0.0, 0.0, -1, 0.0, 0.0, 3.0]), (1, [0.0, 1, 1, -1, 0.0, 0.0, -1, 0.0, 0.0, 8.0]), (1, [0.0, 1, 1, -1, 0.0, 0.0, -1, 0.0, 1, 4.0]), (1, [0.0, 1, 1, -1, -1, 0.0, -1, 0.0, 1, 0.0]), (1, [1, 1, 1, -1, -1, 0.0, -1, 0.0, 1, 7.0]), (1, [1, 1, 1, -1, -1, 0.0, -1, -1, 1, 5.0]), (-1, [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0]), (-1, [0.0, 0.0, 0.0, 0.0, 1, 0.0, 0.0, 0.0, 0.0, 6.0]), (-1, [0.0, 0.0, 0.0, 0.0, 1, 0.0, -1, 0.0, 0.0, 2.0]), (-1, [0.0, 0.0, 1, 0.0, 1, 0.0, -1, 0.0, 0.0, 3.0]), (-1, [0.0, 0.0, 1, -1, 1, 0.0, -1, 0.0, 0.0, 8.0]), (-1, [0.0, 0.0, 1, -1, 1, 0.0, -1, 0.0, 1, 0.0]), (-1, [-1, 0.0, 1, -1, 1, 0.0, -1, 0.0, 1, 7.0]), (-1, [-1, 0.0, 1, -1, 1, 0.0, -1, 1, 1, 5.0]), (-1, [-1, 0.0, 1, -1, 1, -1, -1, 1, 1, 1.0]), (0, [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]), (0, [0.0, 1, 0.0, 0

In [0]:
train = pd.read_csv("./dataset1.csv").values
print(train.shape)
print(train[:10])

(38076, 10)
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  3.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  8.]
 [ 0.  0.  0.  1.  0.  0.  0.  0. -1.  5.]
 [ 0.  0.  0.  1.  0.  1.  0.  0. -1.  0.]
 [-1.  0.  0.  1.  0.  1.  0.  0. -1.  7.]
 [-1.  0.  0.  1.  0.  1.  0.  1. -1.  1.]
 [-1. -1.  0.  1.  0.  1.  0.  1. -1.  2.]
 [-1. -1.  1.  1.  0.  1.  0.  1. -1.  6.]
 [-1. -1.  1.  1.  0.  1. -1.  1. -1.  4.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  5.]]


In [0]:
train = pd.read_csv("./dataset.csv").values
print(train.shape)
print(train[:10])

(7399, 10)
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  3.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  1.]
 [ 0. -1.  0.  1.  0.  0.  0.  0.  0.  8.]
 [ 0. -1.  0.  1.  0.  0.  0.  0.  1.  6.]
 [ 0. -1.  0.  1.  0.  0. -1.  0.  1.  0.]
 [ 1. -1.  0.  1.  0.  0. -1.  0.  1.  7.]
 [ 1. -1.  0.  1.  0.  0. -1. -1.  1.  5.]
 [ 1. -1.  0.  1.  0.  1. -1. -1.  1.  4.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  2.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  8.]]
